# Generated by Django 3.0.5 on 2020-11-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('post_id', models.CharField(default='', max_length=255)),
                ('time_create', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('num_likes', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
                ('effect', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FSI_user',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('project_id', models.CharField(default='', max_length=255)),
                ('num_likes', models.IntegerField()),
                ('num_comments', models.IntegerField()),
                ('num_shares', models.IntegerField()),
                ('content', models.TextField()),
                ('time_create', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_id', models.CharField(default='', max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
    ]
