# Generated by Django 3.1.3 on 2020-11-21 03:24

import FSI_Web.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FSI_Web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fsi_user',
            old_name='password',
            new_name='pictureURL',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='fsi_user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_shares',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time_create',
        ),
        migrations.AddField(
            model_name='project',
            name='keyword',
            field=djongo.models.fields.EmbeddedField(default='', model_container=FSI_Web.models.KeyWord),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='page_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='page_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
